apiVersion: v1
kind: Service
metadata:
  name: {{ include "greetapp.fullname" . }}
  labels:
    {{- include "greetapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.greetapp.service.type }}
  ports:
    - port: {{ .Values.greetapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "greetapp.selectorLabels" . | nindent 4 }}
