apiVersion: v1
kind: Service
metadata:
  name: greet-st-app
spec:
  type: NodePort
  selector:
    app: eks-greet-st-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: greet-web-svc
      
